from typing import Optional, Protocol

from rempah_bridge.model import Command, DeviceState


class MqttPort(Protocol):
    def publish(self, topic: str, payload: dict) -> None: ...


class DbPort(Protocol):
    def device_state(self, device_id: str) -> DeviceState: ...
    def insert_telemetry(self, device_id: str, payload: dict) -> None: ...
    def set_last_seen(self, device_id: str, ts: float) -> None: ...
    def get_last_seen(self, device_id: str) -> Optional[float]: ...
    def set_offline(self, device_id: str, offline: bool) -> None: ...
    def note_first_contact(self, device_id: str, ts: float) -> None: ...
    def is_known_device(self, device_id: str) -> bool: ...
    def record_unknown_message(self, device_id: str, topic: str, payload: dict) -> None: ...
    def list_devices(self) -> list[str]: ...
    def mark_command(self, command_id: str, status: str) -> None: ...
    def set_device_state(self, device_id: str, mode: str, ts: str) -> None: ...
    def insert_alert(self, device_id: str, kind: str, value: float, ts: str) -> None: ...
    def update_estimate(self, device_id: str, estimated_yield_l: float, ts: str) -> None: ...
    def pending_commands(self) -> list[Command]: ...
    def open_pending_batch(self, device_id: str, ts: str) -> None: ...
    def close_active_batch(self, device_id: str, ts: str) -> None: ...
    def interrupt_active_batch(self, device_id: str, ts: str) -> None: ...
    def resume_interrupted_batch(self, device_id: str) -> bool: ...
    def purge_old_sensor_logs(self) -> None: ...
